@Library("jenlib") _

final String PROJECT_NAME = "much-demos-such-wow"

boolean deploy = env.GERRIT_EVENT_TYPE == "change-merged"

try {
	withCcache() {
		wafDefaultPipeline(
			projects           : ["${PROJECT_NAME}"],
			container          : [app: "dls"],
			moduleOptions      : [modules: ["ppu-toolchain"]],
			testSlurmResource  : [partition: "cube", wafer: 62, "fpga-without-aout": 0],
			preTestHook        : { configureHxCubeBitfile() },
			testOptions        : "--test-execall -j1",
			setupOptions       : "--release-branch=ebrains-1.0",
			notificationChannel: "#jenkins-trashbin",  // success is checked globally
			configureInstallOptions: "--build-profile=ci",
			ignoreGerritChanges: deploy
		)
	}

	stage("Archive Results") {
		runOnSlave(label: "frontend") {
			archiveArtifacts("build/${PROJECT_NAME}/**/*")
			publishHTML([allowMissing: false,
			             reportDir   : "build/${PROJECT_NAME}/html",
			             reportFiles : "index.html",
			             reportName  : "HTML Output"])
		}
	}

	conditionalStage(name: "Deployment to GitHub Pages", skip: !deploy) {
		runOnSlave(label: "frontend") {
			dir("build/much-demos-such-wow/jupyter") {
				jesh("git init")
				jesh("git add *.ipynb _static")
				jesh("git commit -m \"build ${currentBuild.displayName}\"")
				jesh("git remote add origin git@github-brainscales2-demos_jupyter-notebooks:electronicvisions/brainscales2-demos.git")
				lock("much-demos-such-wow_GITHUB-UPLOAD") {
					jesh("git push -f origin HEAD:jupyter-notebooks")
				}
			}
		}
	}
} catch (Throwable t) {
	notifyFailure(mattermostChannel: "#1nicedemo")
	notifyFailure(mattermostChannel: "#dls-software")
	throw t
}

if (currentBuild.currentResult != "SUCCESS") {
	notifyFailure(mattermostChannel: "#1nicedemo")
	notifyFailure(mattermostChannel: "#dls-software")
}
