@Library("jenlib") _

final String PROJECT_NAME = "much-demos-such-wow"

try {
	withCcache() {
		wafDefaultPipeline(
			projects           : ["${PROJECT_NAME}"],
			container          : [
				app: "dls",
				singularityArgs: "--overlay /containers/overlays/2021-09-27_bullseye_texlive.img"
			],
			moduleOptions      : [modules: ["ppu-toolchain"]],
			testSlurmResource  : getHxTestResource(3),
			preTestHook        : { configureHxCubeBitfile() },
			testOptions        : "--test-execall -j1",
			notificationChannel: "#jenkins-trashbin",  // success is checked globally
			configureInstallOptions: "--build-profile=ci",
		)
	}

	stage("Archive Results") {
		runOnSlave(label: "frontend") {
			archiveArtifacts("build/${PROJECT_NAME}/**/*")
			publishHTML([allowMissing: false,
			             reportDir   : "build/${PROJECT_NAME}/html/html",
			             reportFiles : "index.html",
			             reportName  : "HTML Output"])
		}
	}

} catch (Throwable t) {
	notifyFailure(mattermostChannel: "#dls-software")
	throw t
}

if (currentBuild.currentResult != "SUCCESS") {
	notifyFailure(mattermostChannel: "#dls-software")
}
